name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - test  # Change this to 'test' for staging or testing
  pull_request:
    branches:
      - test  # Change this to 'test' for staging or testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Change this if you're using another version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Ensure you have a test script in package.json

      - name: Lint the code
        run: npm run lint  # Optional, if you use ESLint

      - name: Build the application
        run: npm run build  # Only if you have a build process

      - run: |
            touch .env
            echo "${{secrets.PROD_ENV_FILE}}" > .env
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test' && success()  # Ensure it's for 'test' branch

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd ${{ secrets.EC2_PATH }}
            git pull origin test  # Pull from the 'test' branch
            npm install
            pm2 restart app --interpreter ts-node  # Use the name you assigned when starting the app
