name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Lint the code
        run: npm run lint || true

      - name: Build the application
        run: npm run build

      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test' && success()

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.8 # Update to a later version
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 1h
          command_timeout: 30m  
          port: 22
          script: |
            cd ${{ secrets.EC2_PATH }} || exit 1
            git pull origin test || exit 1  
            npm install || exit 1
            pm2 restart app --interpreter ts-node || exit 1
